// Type definitions for Cloudflare Workers environment bindings
// Generated by wrangler/types — do not edit manually

interface Env {
  // Secrets (set via `wrangler secret put <NAME>`)
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  SUPABASE_JWT_SECRET: string;
  DATABASE_URL: string;

  // Vars (set in wrangler.toml)
  LOG_LEVEL: string;
}
